config/routes.rb
Rails.application.routes.draw do
 resources :artists , only: [:show, :index]

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists= Artist.all
  end

  def show
    @artist= Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container">

<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <img src="<%= artist.image_url%>" alt=<%= artist.name %>>
        <div class="caption">
          <h3><%= artist.name %></h3>
          <p><%= link_to "Ver más", artist_path(artist), class: "btn btn-primary  btn-block" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1><%= @artist.name %></h1>
      <h3>Album(<%= @artist.albums.count %>)</h3>
      <% @artist.albums.each do |album| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <img src="<%= album.image_url%>" alt=<%= album.name %>>
          <div class="caption">
            <h3><%= album.name %></h3>
            <p><%= album.released_at %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <img src="<%= @artist.image_url%>" alt="<%= @artist.name%>">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Real Music</a>
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to "Artists", artists_path %>
      </li>
      <li>
        <a href="#">My Music</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My profile <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
<%= yield %>

</body>
</html>